### PR TITLE
Add route keys/{kid}/jwk.json

### PR DESCRIPTION
**Pull request by Equanox**
JWK (https://tools.ietf.org/html/rfc7517) format seems to be a bit more common to expose the public key. This allows us to be more flexible in checking JWT validity.

I think it won't break anything as the pem route is still functional.  The JWK creation is based on  https://github.com/lestrrat-go/jwx .

### CODE REVIEW

**Comment by joe94** [comment]
I agree. This is great! 😄 Thanks, @Equanox! FYI: there are some failing tests in travis though. We should fix that before merging.

**Comment by Equanox** [comment]
Thx guys, will fix the failing tests. @johnabass didnt know exactly how to react properly to the Content-Type, is there a example in one of your repos?  Then i will try to do a follow up PR.

**Comment by johnabass** [comment]
> Thx guys, will fix the failing tests. @johnabass didnt know exactly how to react properly to the Content-Type, is there a example in one of your repos? Then i will try to do a follow up PR.

We're in the process of retooling around content negotiation.  We should just push this PR to master for now.  We can redo an URLs or content negotation after we settle on a solution.

**Comment by johnabass** [comment]
https://github.com/xmidt-org/themis/releases/tag/v0.4.4 has this PR in it.

I did change things a bit in https://github.com/xmidt-org/themis/pull/53.  Notably, the specific URLs are `/keys/{kid}/key.json` and `/keys/{kid}/keys.pem` when not using content negotiation.

**Pull request merged**
